services:
  mysql:
    image: mysql:8.0
    container_name: mysql-skripsi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skripsi_m0518036_muhammad-priyo-utomo
    ports:
      - "8111:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-skripsi_m0518036_muhammad-priyo-utomo
    restart: always
    ports:
      - "8080:80" # Port phpmyadmin => http://localhost:8080/
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 500M # ⬅️ Atur max limit upload sql. 500M = 500 MB

volumes:
  mysql_data:
